### ISSUE TITLE
Check for filling field type "image" possibilites

### ISSUE THREAD

**Issue by tertek** [Research-IT-Swiss-TPH/pdf-api#2]
Check if there is an open source possibility to fill images into pdf form fields.
Or implement ourselves.
- [x] Difference calculation filled / unfilled free PDF.
- [x] Check for PDF Spec Parsers

**Comment by edenst-TPH** [comment]
pdfimages (Teil der poppler-utils)  kann images eines PDFs auslisten und auch exportieren
https://arunmozhi.in/2019/01/29/replacing-image-in-a-pdf-with-python/
https://www.cyberciti.biz/faq/easily-extract-images-from-pdf-file/

install poppler, it comes with pdfimages
`sudo apt-get install poppler-utils`
`pdfimages --version`

let pdftk free the pdf (and uncompress it for better handling)
`pdftk my.pdf output myFreeUncompressed.pdf uncompress`

list images-in-pdf, incl Object ID
`pdfimages -list myFreeUncompressed.pdf`

export images-from-pdf-file, named by (image id??)
`pdfimages myFreeUncompressed.pdf ./export/`

**Comment by tertek** [comment]
@edenst-TPH Wofür wäre das exportieren nützlich?
Mir fällt gerade kein Fall ein.

**Comment by tertek** [comment]
Ich habe pyMuPDF getestet:

```python
# main.py                                                      

import fitz # imports the pymupdf library

doc = fitz.open("test_img_uc.pdf") # open a document
page = doc[0]
img_list = page.get_images(full=True) # a list of all images on that page

item = img_list[0]
bbox = page.get_image_bbox(item)

print(img_list)

print(bbox)

```
![Image](https://github.com/Research-IT-Swiss-TPH/pdf-api/assets/75415872/c4f1694a-6d38-4d41-863c-3bd69be08c15)

Man müsste noch schauen, ob man anhand der ID, das Bild ersetzen kann.

**Comment by edenst-TPH** [comment]
> @edenst-TPH Wofür wäre das exportieren nützlich? Mir fällt gerade kein Fall ein.

Wenn man das Bild welches durch den QR ersetzt werden soll, als Bild erkennen und mit dem Image-List Eintrag matchen kann, hat man dort die PDF object ID - matchen ist das Problem, evtl hilft die genaue Abmessung & Filesize?
[imglist.txt](https://github.com/Research-IT-Swiss-TPH/pdf-api/files/13714595/imglist.txt)

**Comment by tertek** [comment]
Image filling has been identified as a rather cumbersome task and will be left out for now.
