### ISSUE TITLE
Development Setup

### ISSUE THREAD

**Issue by tertek** [Research-IT-Swiss-TPH/pdf-api#7]

**Comment by edenst-TPH** [comment]
I start in the user home, right?
the clone cmd gives me an access denied error
git clone git@github.com:Research-IT-Swiss-TPH/pdf-api.git
=> should I attempt to login? or maybe download the repo as zip, unzip it to the right place, run the composer / docker cmds ?
https://github.com/Research-IT-Swiss-TPH/pdf-api

**Comment by tertek** [comment]
Have you setup SSH?
https://docs.github.com/en/authentication/connecting-to-github-with-ssh

**Comment by edenst-TPH** [comment]
Setup in wsl Ubuntu, pubkey to my github account => ssh login ok, git clone worked, created ~/pdf-api
$ composer install --working-dir=./app => OK
$ sudo docker compose -f compose.dev.yml 
=> works, but:
[+] Running 3/3
 ✘ nginx Error                                                                                                                              1.0s
 ✘ postgres Error                                                                                                                           1.0s
 ✘ adminer Error                                                                                                                            1.0s
Error response from daemon: Head "https://registry-1.docker.io/v2/library/adminer/manifests/latest": Get "https://auth.docker.io/token?scope=repository%3Alibrary%2Fadminer%3Apull&service=registry.docker.io": read tcp 172.28.235.71:53040->34.226.69.105:443: read: connection reset by peer

**Comment by tertek** [comment]
This is related to the self-signed certificate issue of the company network (as noted here: https://github.com/Research-IT-Swiss-TPH/pdf-api#notice)

**Comment by tertek** [comment]
The development setup has been successfully setup.
